language: r
cache: packages
dist: trusty
os: linux

r_github_packages:
  - sckott/httpcode

r_binary_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
